version: '3.7'
services:
  ipfs:
    build:
      context: ipfs/
      network: host
    network_mode: host
    container_name: vx_ipfs
    volumes:
      - ./ipfs/export:/export
      - ./ipfs/data:/data/ipfs
      - ../config/secrets/ipfs/swarm.key:/data/ipfs/swarm.key
      - /var/run/docker.sock:/var/run/docker.sock
